version: "3"

services:
  gpmt-net:
    build:
        dockerfile: Dockerfile
        context: ./
    networks:
      - gpmt-default
    environment:
      - MONGO_URL=mongodb://gpmt-mongo:27017/gpmt
      - PORT=8088
    ports:
      - "8088:8088"

networks:
  gpmt-default:
    name: gpmt-default