apiVersion: apps/v1
kind: Deployment
metadata:
    name: gpmt-net
    namespace: "default"
spec:
    selector:
        matchLabels:
            app: gpmt-net
    template:
        metadata:
            labels:
                app: gpmt-net
        spec:
            containers:
            - name: gpmt-net
              image: gpmtcontainerregistry.azurecr.io/gpmt-api
              imagePullPolicy: Always
              env:
              - name: PORT
                value: "80"
              - name: MONGO_URL
                valueFrom:
                  secretKeyRef:
                    name: cosmosdb
                    key: url
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: "registry-token"